@startuml
title Теплый дом. Диаграмма контейнеров

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")
Person(admin, "Администратор", "Администратор системы умный дом")
System(SmartHouse, "система Умный дом", "Система управления отоплением домов и умными устройствами")

Container_Boundary(SmartHouse, "FitLife System") {
  Container(WebApp, "Web приложение", "react", "Панель управления устройствами")
  Container(WebAppAdmin, "Web приложение администратора", "react", "Панель администратора")
  Container(GateWay, "API шлюз", "Go", "Маршрутизация запросов")
  Container(UserAccess, "Управление пользователями", "Go", "Управление данных пользователей")
  ContainerDb(UserAccessDb, "Database Пользователи", "PostgreSQL", "Хранение данных пользователей")
  Container(DeviceRepository, "Реестр устройств", "Go", "Управление устройствами, их расположении и доступности для пользователя")
  ContainerDb(DeviceRepositoryDb, "Database устройства", "PostgreSQL", "Хранение информации об устройствах, их расположении")
  Container(Automatic, "Модуль управления и автоматизацией", "Go", "Управление устройствами по сценариям и графикам")
  ContainerDb(AutomaticDb, "База данных автоматизации", "PostgreSQL", "Хранение сценариев и графиков управления устройствами")
  Container(Notification, "Модуль оповещений", "Go", "Формирование сообщений по определенным событиям")
  ContainerDb(NotificationDb, "База данных оповещений", "Go", "Хранение условий формирования оповещений")
  Container(Telemetry, "Модуль телеметрии", "Go", "Обработка и хранение телеметрии датчиков и устройств")
  ContainerDb(TelemetryDatabase, "База данных телеметрии", "PostgreSQL", "Временные ряды состояний датчиков и устройств")
  Container(DeviceControl, "Взаимодействие устройствами", "Go", "Взаимодействие с устройствами")    
}

System_Ext(PaidService, "Сервис оплаты", "")
System_Ext(SmartDevice, "Устройства", "Умные устройства, датчики и регуляторы отопления (экосистема партнеров)")
System_Ext(Messengers, "Мессендеры", "Доставка событий")

Rel(user, WebApp, "Управляет устройствами своего дома")
Rel(admin, WebAppAdmin,"Управляет пользователями и доступом к датчикам")
Rel(WebApp, GateWay, "Обработка запросов")
Rel(WebAppAdmin, GateWay, "Обработка запросов")
Rel(GateWay, UserAccess, "Авторизация, управление")
Rel(GateWay, Telemetry, "Получение отчетов и данных в реальном времени")
Rel(GateWay, Automatic, "Управление автоматизацией")
Rel(GateWay, Notification, "Управление оповещениями")
Rel(GateWay, DeviceRepository, "Получение доступных устройств, регистрация новых")
Rel(UserAccess, UserAccessDb, "Запись/чтение данных")
Rel(UserAccess, PaidService, "Оплата подписки")
Rel(Telemetry,TelemetryDatabase,"Запись/чтение данных")
Rel(Automatic, AutomaticDb, "Запись/чтение данных")
Rel(Automatic, DeviceRepository, "Получение списка устройств управления")
Rel(Automatic, DeviceControl, "Управление и получение данных")
Rel(Notification, Telemetry, "Определение формирования событий")
Rel(Notification, Messengers, "Доставка событий")
Rel(Notification, UserAccess, "Получение контактов для отправления событий")
Rel(Notification, NotificationDb, "Получение контактов для отправления событий")
Rel(DeviceControl, DeviceRepository, "Получение списка устройств")
Rel(DeviceControl, Telemetry, "Передача показания датчиков и телеметрии")
Rel(DeviceControl,SmartDevice,"Взаимодействие с экосистемой")
Rel(DeviceRepository, DeviceRepositoryDb, "Запись/чтение данных")

@enduml