@startuml
title Теплый дом. Модуль управления и автоматизацией. Диаграмма компонентов

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


Container_Boundary(SmartHouse, "Система Умный дом") {
  Container(GateWay, "API шлюз", "Go", "Маршрутизация запросов")
  Container(Automatic, "Модуль управления и автоматизацией", "Go", "Управление устройствами по сценариям и графикам")
  ContainerDb(AutomaticDb, "База данных автоматизации", "PostgreSQL", "Хранение сценариев и графиков управления устройствами")
  Container(DeviceControl, "Взаимодействие устройствами", "Go", "Взаимодействие с устройствами")    
}

Container(Automatic, "Модуль управления и автоматизацией", "Go") {
  Component(ApiHandler, "API", "Обработка запросов")
  Component(PollingCircle, "UserController", "Manages user profiles")
  Component(ScheduleController, "ScheduleController", "Manages schedules")
  Component(PaymentController, "PaymentController", "Handles payment processing")
  Component(Aggragator, "Service Layer", "Бизнес логика")
  Component(RepositoryLayer, "Repository Layer", "Доступ к БД")
}

Rel(GateWay, Automatic, "Управление автоматизацией")
Rel(Automatic, AutomaticDb, "Запись/чтение данных")
Rel(Automatic, DeviceRepository, "Получение списка устройств управления")
Rel(Automatic, DeviceControl, "Управление и получение данных")
@enduml