@startuml
title Теплый дом. Взаимодействие устройствами. Диаграмма компонентов

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml


Container_Boundary(SmartHouse, "Система Умный дом") {
  Container(Telemetry, "Модуль телеметрии", "Go", "Обработка и хранение телеметрии датчиков и устройств")
  Container(DeviceRepository, "Реестр устройств", "Go", "Управление устройствами, их расположении и доступности для пользователя")
  Container(Automatic, "Модуль управления и автоматизацией", "Go", "Управление устройствами по сценариям и графикам")
  Container(DeviceControl, "Взаимодействие устройствами", "Go", "Взаимодействие с устройствами")    
}

System_Ext(SmartDevice, "Устройства", "Умные устройства, датчики и регуляторы отопления (экосистема партнеров)")

Container(DeviceControl, "Взаимодействие устройствами", "Go") {
  Component(CommandWrapper, "Обработчик команд", "Подготавливает команды к экосистеме устройств")
  Component(DataSender, "Модуль подготовки данных", "Формирует запрос для отправления")
  Component(Scheduler, "Планировщик взаимодействия с устройствами", "Определяет последовательность опроса устройств")
  Component(AutomaticConsumer, "Потребитель сообщений от модуля управления", "Handles payment processing")
  Component(DeviceProducer, "Producer команд", "Отправление ")
  Component(DeviceConsumer, "Потребитель сообщений от устройств", "Получение измеренных значений и состояний")
}

Rel(Automatic, AutomaticConsumer, "Управление и получение данных")
Rel(AutomaticConsumer, CommandWrapper, "Обработка команд")
Rel(CommandWrapper, DeviceProducer, "Передача команд")
Rel(Scheduler, DeviceRepository, "Получение списка устройств")
Rel(Scheduler, DeviceProducer, "Опрос устройств")
Rel(DeviceConsumer, DataSender, "Подготовка данных")
Rel(DataSender, Telemetry, "Передача данных")
Rel(DeviceConsumer, Scheduler, "Опрос устройств")
Rel(SmartDevice,DeviceConsumer,"Взаимодействие с устройствами (протокол экосистеми партнера)")
Rel(DeviceProducer,SmartDevice,"Взаимодействие с устройствами (протокол экосистеми партнера)")
@enduml