@startuml
title Теплый дом. Web приложение. Диаграмма компонентов

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")

Container_Boundary(SmartHouse, "Система Умный дом") {
  Container(WebApp, "Web приложение", "react", "Панель управления устройствами")
  Container(GateWay, "API шлюз", "Go", "Маршрутизация запросов")
}

Container(WebApp, "Web приложение", "Go") {
  Component(LoginModule, "Модуль аутентификации", "Страница входа в систему")
  Component(TelemetryReport, "Модуль телеметрии", "Визуализация текущих значений, графиков, отчетов")
  Component(DeviceRegistryManage, "Модуль реестр устройств", "Доступ к просмотру зарегистрированных устройств, регистрация новых")
  Component(NotifyManage, "Модуль управление оповещениями", "Доступ к просмотру зарегистрированных оповещений, добавление и редактирование новых")
  Component(AutomaticManage, "Модуль управление расписанием и автоматизацией", "Доступ к управлению расписанием и логикой работы устройств")
}

Rel(user, LoginModule,"Управляет пользователями и доступом к датчикам")
Rel(user, TelemetryReport,"Управляет пользователями и доступом к датчикам")
Rel(user, DeviceRegistryManage,"Управляет пользователями и доступом к датчикам")
Rel(user, NotifyManage,"Управляет пользователями и доступом к датчикам")
Rel(user, AutomaticManage,"Управляет пользователями и доступом к датчикам")
Rel(LoginModule, GateWay, "Обработка запросов")
Rel(TelemetryReport, GateWay, "Обработка запросов")
Rel(DeviceRegistryManage, GateWay, "Обработка запросов")
Rel(NotifyManage, GateWay, "Обработка запросов")
Rel(AutomaticManage, GateWay, "Обработка запросов")
@enduml