@startuml
title Теплый дом. Диаграмма контейнеров

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")
Person(admin, "Администратор", "Администратор системы умный дом")
System(SmartHouse, "система Умный дом", "Система управления отоплением домов и умными устройствами")

Container_Boundary(SmartHouse, "FitLife System") {
  Container(WebApp, "Web приложение", "javascript", "Обработка действий пользователей")
  Container(UserAccess, "Доступ пользователей", "Go", "Управление данных пользователей")
  ContainerDb(UserAccessDb, "Database Пользователи", "PostgreSQL", "Хранение данных пользователей")

  Container(Automatic, "Реализация автоматических сценариев", "Go", "Управление устройствами по сценариям и графикам")
  ContainerDb(AutomaticDb, "База данных автоматизации", "PostgreSQL", "Хранение сценариев и графиков управления устройствами")
  
  Container(DeviceControl, "Управление устройствами", "Go", "Взаисодействие с умными устройствами и регуляторами")
  Container(Telemetry, "Обработка телеметрии", "Go", "Управление регуляторами отопления и умными устройствами")
  ContainerDb(DeviceDatabase, "Devices database", "PostgreSQL", "Хранение данных об устройствах, текущее состояние")
  ContainerDb(TelemetryDatabase, "База данных телеметрии", "PostgreSQL", "Временные ряды состояний датчиков и устройств")
}

System_Ext(PaidService, "Сервис оплаты", "")
System_Ext(SmartDevice, "Устройства", "Умные устройства, датчики и регуляторы отопления")


Rel(user, WebApp, "Управляет устройствами своего дома")
Rel(admin, WebApp,"Управляет пользователями и доступом к датчикам")


Rel(WebApp, UserAccess, "Авторизация, управление")
Rel(UserAccess, UserAccessDb, "Запись/чтение данных")
Rel(WebApp, DeviceControl, "Управление и получение данных")
Rel(WebApp, Telemetry, "Получение отчетов телеметрии")
Rel(WebApp, Automatic, "Получение отчетов телеметрии")
Rel(Automatic, AutomaticDb, "Запись/чтение данных")
Rel(Automatic, DeviceControl, "Управление и получение данных")
Rel(DeviceControl,DeviceDatabase,"Получение информации об устройствах")
Rel(DeviceControl,Telemetry,"Сохранение телеметрии")
Rel(Telemetry,TelemetryDatabase,"Сохранение телеметрии")
Rel(DeviceControl,SmartDevice,"Команды управления")
Rel(SmartDevice,DeviceControl,"Получение данных")
Rel(UserAccess, PaidService, "Оплата подписки")
@enduml